// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package form

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ImageForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"uploadComponent()\" class=\"my-4\"><label for=\"input-files\"><input @change=\"addFiles($event)\" type=\"file\" id=\"input-files\" name=\"files\" multiple hidden><div id=\"viewer\" class=\"w-full min-h-40 flex justify-center items-center flex-wrap p-4 border-dashed border-2 border-gray-400 rounded text-center\"><template x-if=\"files.length == 0\"><span class=\"text-gray-500\">Arrastra tus archivos aquí o haz click para seleccionar</span></template><template x-for=\"(file, index) in files\"><div class=\"w-20 h-20 m-1 relative\"><img :src=\"URL.createObjectURL(file)\" class=\"w-full h-full object-cover rounded\"> <button type=\"button\" @click=\"removeFile(index)\" class=\"absolute top-0 right-0 bg-red-500 text-white rounded-full w-5 h-5 flex items-center justify-center text-xs hover:bg-red-600 transition-colors\">X</button></div></template></div></label></div><script>\n    function uploadComponent(){\n      return {\n        files: [],\n        addFiles(event){\n          const newFiles = Array.from(event.target.files);\n          this.files.push(...newFiles);\n          this.syncInputFiles(event.target);\n        },\n        removeFile(index){\n          this.files.splice(index, 1);\n          this.syncInputFiles(document.getElementById('input-files'));\n        },\n        syncInputFiles(input) {\n          const dataTransfer = new DataTransfer();\n\n          this.files.forEach(file => {\n            dataTransfer.items.add(file);\n          });\n\n          input.files = dataTransfer.files;\n        }\n      }\n    }\n  </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
