// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage(values, errors map[string]string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Admin</title><link rel=\"stylesheet\" href=\"/static/css/output.css\"></head><body class=\"w-full h-dvh\"><div class=\"h-full flex justify-center items-center bg-bluemmy-50\"><div class=\"p-10 rounded-xl shadow-sm shadow-bluemmy-300\"><h1 class=\"text-2xl mb-4 text-bluemmy-600 text-center w-full font-bold\">Iniciar sesión</h1><form action=\"/admin/login\" method=\"POST\"><div class=\"flex flex-col gap-4\"><div class=\"flex flex-col justify-start gap-1\"><label class=\"font-bold\" for=\"inUser\">Usuario</label> <input id=\"inUser\" class=\"p-2 border border-gray-400 rounded-md focus:outline-0 focus:ring focus:ring-bluemmy-400\" type=\"text\"></div><div class=\"flex flex-col justify-start gap-1\"><label class=\"font-bold\" for=\"inPass\">Contraseña</label> <input id=\"inPass\" class=\"p-2 border border-gray-400 rounded-md focus:outline-0 focus:ring focus:ring-bluemmy-400\" type=\"password\"></div><button class=\"py-2 mt-2 bg-bluemmy-500 font-bold text-white rounded hover:bg-bluemmy-600 cursor-pointer\">Ingresar</button></div></form></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
