// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"border-2 h-11 py-2 px-4 content-center font-fredoka border-bluemmy-400 bg-bluemmy-50 m-2 rounded-full lg:my-2 lg:m-auto lg:w-2/3\"><div x-data=\"{open: false}\" class=\"z-50 flex flex-row justify-between items-center\"><div class=\"relative flex flex-row gap-2 z-40\"><img src=\"/static/assets/logo.png\" alt=\"Logo\" class=\"h-6\"><p class=\"text-bluemmy-600\">Giga3D</p></div><div class=\"bg-bluemmy-50 absolute top-0 left-0 w-full p-2 pt-14 sm:static sm:block sm:p-0\" :class=\"{ 'hidden': !open }\"><ul class=\"flex flex-col sm:flex-row text-bluemmy-600 items-center gap-2 sm:justify-center sm:gap-4\"><li class=\"w-5/6 sm:w-min text-center\"><a href=\"/\">Inicio</a></li><li class=\"w-5/6 sm:w-min text-center\"><a href=\"/products\">Productos</a></li></ul></div><button @click=\"open = !open\" :aria-expanded=\"open\" class=\"z-40 relative w-5 h-5 flex items-center justify-center cursor-pointer sm:hidden\"><!-- Hamburguesa --><svg x-show=\"!open\" class=\"w-6 h-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M4 6h16M4 12h16M4 18h16\"></path></svg><!-- Cerrar --><svg x-show=\"open\" class=\"w-6 h-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6 18L18 6M6 6l12 12\"></path></svg></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
